### ISSUE TITLE
Make the frontend more modular

### ISSUE THREAD

**Issue by kaBeech** [SF-Audio-Guild/dm-dash#61]
Like waaaaaaaaay more modular. I want to eventually be able to change up which modules are shown and what is in them with great ease

It will be helpful to break down the views into smaller reusable component pieces

Eventually we may build multiple frontends and may not need this much modularity on the Dashboard, but if we start thinking about this now then this will be easier down the road

**Comment by kaBeech** [comment]
I added the good first issue label because breaking down components is relatively straightforward for good programmers with React experience. Or any good programmers with a passion for clean code

If you don't know what you're doing then check in with @royalsaltmerchant or myself. But don't be afraid - if you think you might be able to help out you probably can with a lil guidance

**Comment by royalsaltmerchant** [comment]
@kaBeech I think after our conversation yesterday, we can sort of just keep pushing in this direction by keeping the idea in the back of our minds. Might just close this ticket since it's less of a "todo" and more of general idea
